# Generated by Django 2.2.5 on 2019-10-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LPRate',
            fields=[
                ('lp_type', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='LP Type')),
                ('lp_rate', models.IntegerField(verbose_name='LP Rate')),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['lp_type'],
                'verbose_name': 'LP Rate',
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('field_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Field ID')),
                ('field_text', models.TextField()),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'ordering': ['field_id'],
                'verbose_name_plural': 'Site Content',
            },
        ),
        migrations.CreateModel(
            name='CourierRoute',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Route ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('m3_pricing', models.IntegerField()),
                ('max_volume', models.IntegerField()),
                ('completion_days', models.IntegerField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('collateral_percent', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'verbose_name': 'Courier Route',
                'ordering': ['route_id'],
            },
        ),
    ]
