# Generated by Django 2.2.5 on 2019-10-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi_app', '0004_auto_20191021_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esimarket',
            name='buy_order_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='esimarket',
            name='daily_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='esimarket',
            name='sell_order_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
