# Generated by Django 3.0.7 on 2020-07-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi_app', '0005_auto_20191021_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esimarket',
            name='lp_type',
            field=models.CharField(choices=[('Guristas', 'Guristas'), ('Sanshas', 'Sanshas'), ('Blood Raiders', 'Blood Raiders'), ('DED', 'DED'), ('None', 'None')], default='None', max_length=100, verbose_name='LP Type'),
        ),
    ]
