# Generated by Django 2.1.7 on 2019-03-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('lp', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('profit', models.IntegerField()),
            ],
        ),
    ]
