# Generated by Django 2.1.7 on 2019-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='date',
            field=models.DateField(),
        ),
    ]
