# Generated by Django 2.2.5 on 2019-09-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0002_auto_20190408_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('cashout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tables_app.Cashout')),
                ('gila_blueprint', models.IntegerField(default=0, verbose_name='Gila')),
                ('worm_blueprint', models.IntegerField(default=0, verbose_name='Worm')),
                ('high_grade_crystal_alpha', models.IntegerField(default=0, verbose_name='High-grade Crystal Alpha')),
                ('high_grade_crystal_beta', models.IntegerField(default=0, verbose_name='High-grade Crystal Beta')),
                ('high_grade_crystal_gamma', models.IntegerField(default=0, verbose_name='High-grade Crystal Gamma')),
                ('high_grade_crystal_delta', models.IntegerField(default=0, verbose_name='High-grade Crystal Delta')),
                ('high_grade_crystal_epsilon', models.IntegerField(default=0, verbose_name='High-grade Crystal Epsilon')),
                ('high_grade_crystal_omega', models.IntegerField(default=0, verbose_name='High-grade Crystal Omega')),
                ('mid_grade_crystal_alpha', models.IntegerField(default=0, verbose_name='Mid-grade Crystal Alpha')),
                ('mid_grade_crystal_beta', models.IntegerField(default=0, verbose_name='Mid-grade Crystal Beta')),
                ('mid_grade_crystal_gamma', models.IntegerField(default=0, verbose_name='Mid-grade Crystal Gamma')),
                ('mid_grade_crystal_delta', models.IntegerField(default=0, verbose_name='Mid-grade Crystal Delta')),
                ('mid_grade_crystal_epsilon', models.IntegerField(default=0, verbose_name='Mid-grade Crystal Epsilon')),
                ('mid_grade_crystal_omega', models.IntegerField(default=0, verbose_name='Mid-grade Crystal Omega')),
                ('succubus_blueprint', models.IntegerField(default=0, verbose_name='Succubus')),
                ('high_grade_amulet_alpha', models.IntegerField(default=0, verbose_name='High-grade Amulet Alpha')),
                ('high_grade_amulet_beta', models.IntegerField(default=0, verbose_name='High-grade Amulet Beta')),
                ('high_grade_amulet_gamma', models.IntegerField(default=0, verbose_name='High-grade Amulet Gamma')),
                ('high_grade_amulet_delta', models.IntegerField(default=0, verbose_name='High-grade Amulet Delta')),
                ('high_grade_amulet_epsilon', models.IntegerField(default=0, verbose_name='High-grade Amulet Epsilon')),
                ('high_grade_amulet_omega', models.IntegerField(default=0, verbose_name='High-grade Amulet Omega')),
                ('mid_grade_amulet_alpha', models.IntegerField(default=0, verbose_name='Mid-grade Amulet Alpha')),
                ('mid_grade_amulet_beta', models.IntegerField(default=0, verbose_name='Mid-grade Amulet Beta')),
                ('mid_grade_amulet_gamma', models.IntegerField(default=0, verbose_name='Mid-grade Amulet Gamma')),
                ('mid_grade_amulet_delta', models.IntegerField(default=0, verbose_name='Mid-grade Amulet Delta')),
                ('mid_grade_amulet_epsilon', models.IntegerField(default=0, verbose_name='Mid-grade Amulet Epsilon')),
                ('mid_grade_amulet_omega', models.IntegerField(default=0, verbose_name='Mid-grade Amulet Omega')),
            ],
        ),
        migrations.AddField(
            model_name='cashout',
            name='lp_type',
            field=models.CharField(choices=[('gu', 'Guristas'), ('sa', 'Sanshas')], default='Guristas', max_length=100),
            preserve_default=False,
        ),
    ]
