# Generated by Django 2.2.5 on 2019-09-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0003_auto_20190920_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='ItemList',
        ),
    ]
