# Generated by Django 2.2.5 on 2019-09-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0004_auto_20190920_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='gila_blueprint',
            field=models.IntegerField(default=0, verbose_name='Gila Blueprint'),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='succubus_blueprint',
            field=models.IntegerField(default=0, verbose_name='Succubus Blueprint'),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='worm_blueprint',
            field=models.IntegerField(default=0, verbose_name='Worm Blueprint'),
        ),
    ]
