# Generated by Django 2.2.5 on 2019-09-21 01:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0006_itemlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashout',
            name='items',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemList',
        ),
    ]
