# Generated by Django 2.2.5 on 2019-09-21 01:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import tables_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0007_auto_20190921_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='items',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=tables_app.models.items_default),
        ),
    ]
