# Generated by Django 2.2.5 on 2019-09-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0008_auto_20190921_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='lp_type',
            field=models.CharField(choices=[('gu', 'Guristas'), ('sa', 'Sanshas')], max_length=2),
        ),
    ]
