# Generated by Django 2.2.5 on 2019-09-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0010_auto_20190921_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='profit',
            field=models.BigIntegerField(),
        ),
    ]
