#cloud-config
users:
  - name: ${username}
    ssh-authorized-keys:
        - ${pub_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
runcmd:
  - apt-get -y update
  - apt-get -y upgrade
  - apt-get -y install haveged
  - apt -y install docker.io
  - systemctl start docker
  - systemctl enable docker
  - curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - gpasswd -a ${username} docker
  - apt -y autoremove
  - git config --global user.name "${fullname}"
  - git config --global user.email "${email}"
  - reboot
