# Generated by Django 3.0.7 on 2020-07-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fittings',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ship', models.CharField(max_length=100)),
                ('fitting', models.TextField()),
            ],
        ),
    ]
