# Generated by Django 3.0.7 on 2020-07-12 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fittings',
            options={'ordering': ['ship'], 'verbose_name': 'Fittings', 'verbose_name_plural': 'Fittings'},
        ),
    ]
