version: '3.7'

services:

    nginx:
        image: nginx:1.19.0-alpine
        volumes:
            - ./config/nginx:/etc/nginx/conf.d
            - ./config/certbot/conf:/etc/letsencrypt
            - ./config/certbot/www:/var/www/certbot
        ports:
            - 80:80
            - 443:443

    certbot:
        image: certbot/certbot
        volumes:
            - ./config/certbot/conf:/etc/letsencrypt
            - ./config/certbot/www:/var/www/certbot
