# Generated by Django 2.2.5 on 2019-10-06 16:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import esi_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsiCharacter',
            fields=[
                ('character_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('character_owner_hash', models.CharField(max_length=255)),
                ('character_name', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=4096)),
                ('access_token_expires', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=200)),
                ('assoc_user', models.ForeignKey(db_column='assoc_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Owner')),
                ('character_lp', django.contrib.postgres.fields.jsonb.JSONField(default=esi_app.models.json_default)),
            ],
            options={
                'ordering': ['assoc_user'],
                'verbose_name': 'Character',
            },
        ),
        migrations.CreateModel(
            name='EsiMarket',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Type ID')),
                ('type_name', models.CharField(max_length=200)),
                ('market_orders', django.contrib.postgres.fields.jsonb.JSONField(default=esi_app.models.json_default)),
                ('buy_order_max', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sell_order_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('history_last_updated', models.DateTimeField(default=esi_app.models.datetime_default)),
                ('market_history', django.contrib.postgres.fields.jsonb.JSONField(default=esi_app.models.json_default)),
                ('orders_last_updated', models.DateTimeField(default=esi_app.models.datetime_default)),
                ('daily_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('daily_isk', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('lp_type', models.CharField(choices=[('Guristas', 'Guristas'), ('Sanshas', 'Sanshas'), ('DED', 'DED'), ('None', 'None')], default='None', max_length=100, verbose_name='LP Type')),
            ],
            options={
                'verbose_name': 'Market Data',
                'ordering': ['type_id'],
                'verbose_name_plural': 'Market Data',
            },
        ),
    ]
