# Generated by Django 2.2.5 on 2019-10-13 20:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import esi_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('esi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esicharacter',
            name='character_bookmarks',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=esi_app.models.json_default),
        ),
    ]
