# Generated by Django 2.1.7 on 2019-04-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi_app', '0002_auto_20190404_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='esicharacter',
            name='assoc_user',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
