# Generated by Django 2.2.5 on 2019-10-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi_app', '0003_auto_20191021_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esimarket',
            name='history_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esimarket',
            name='orders_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
