# Generated by Django 2.1.7 on 2019-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi_app', '0003_esicharacter_assoc_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esicharacter',
            options={'ordering': ['assoc_user'], 'verbose_name': 'Character'},
        ),
        migrations.AlterField(
            model_name='esicharacter',
            name='assoc_user',
            field=models.CharField(max_length=200, verbose_name='Owner'),
        ),
    ]
